version: '3.4'

services:
  sqlserver:
    image: 'mcr.microsoft.com/mssql/server:2022-latest'
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'Asdf@1234'
      MSSQL_PID: 'Express'
    ports:
       - '1433:1433'
    restart: always
    volumes:
        - 'sqlserver-data:/var/opt/mssql'
  mongodb_container:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    volumes:
      - 'mongodb-data:/data/db'
    restart: always
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    restart: always

